Fix misc
WildCodeSchool/2022-03-JS-Lille-project-3-g2-wim pull request #105
Opened 2022-07-25 13:03 UTC by ilalande

2022-07-25 13:14 UTC, ThomasDCW submitted a review, later dismissed
ok for me

2022-07-25 13:59 UTC, LuigiMenez approved these changes
Ok for me.

2022-07-25 13:59 UTC, LuigiMenez commented on frontend/src/components/SignUp/index.jsx
> +        toast.success(`Félicitations, vous êtes bien inscrit à WIM`, {});
We forgot to remove the braces when we removed the options, right?

2022-07-25 13:59 UTC, LuigiMenez commented on frontend/src/components/SignUp/index.jsx
> +        toast.error(`${e.response.data}`, {});
Same

2022-07-25 14:00 UTC, LuigiMenez requested changes
Fix Minor

2022-07-25 15:22 UTC, ThomasDCW approved these changes

2022-07-26 07:31 UTC, LuigiMenez approved these changes
Ok for me.

2022-07-26 09:25 UTC, LoicBrassart approved these changes
SnE

2022-07-26 09:25 UTC, LoicBrassart commented on frontend/src/components/InfoSchool/index.jsx
> +        setActive(" ");
?

2022-07-26 09:44 UTC, merged