creation routage backend
WildCodeSchool/2022-03-JS-Lille-project-3-g2-wim pull request #2
Opened 2022-06-01 11:56 UTC by n-faycel

2022-06-01 11:58 UTC, ThomasDCW approved these changes

2022-06-01 12:58 UTC, LuigiMenez approved these changes
Ok for me.

2022-06-01 13:18 UTC, LoicBrassart requested changes
A bit of code to remove

2022-06-01 13:18 UTC, LoicBrassart commented on backend/src/models/LessonManager.js
> +    return this.connection.query(`select * from  ${LessonManager.table}`);
No need, it's present in the AbstractManager

2022-06-01 13:47 UTC, LoicBrassart requested changes
A bit of code to remove

2022-06-01 14:00 UTC, n-faycel reviewed
ok

2022-06-01 14:01 UTC, ThomasDCW approved these changes

2022-06-02 07:58 UTC, LuigiMenez approved these changes
Ok for me.

2022-06-02 08:02 UTC, LoicBrassart approved these changes
SnE!

2022-06-02 08:13 UTC, merged