Sign up sign in form
WildCodeSchool/2022-03-JS-Lille-project-3-g2-wim pull request #20
Opened 2022-06-08 15:14 UTC by ThomasDCW

First working version of the frontend form Sign In & Sign Up, designed with material UI

2022-06-08 15:16 UTC, ilalande approved these changes

2022-06-09 08:24 UTC, LuigiMenez requested changes
Isn't it possible to refactor everything into several small components?
Is not disable EsLint

2022-06-09 08:24 UTC, LuigiMenez commented on frontend/src/pages/LogIn/index.jsx
> +                {/* eslint-disable-next-line react/jsx-props-no-spreading */}
Nop

2022-06-09 08:24 UTC, LuigiMenez commented on frontend/src/pages/LogIn/index.jsx
> +                {/* eslint-disable-next-line react/jsx-props-no-spreading */}
Nop

2022-06-09 08:24 UTC, LuigiMenez commented on frontend/src/pages/LogIn/index.jsx
> +  TabPanel.propTypes = {
The proptypes are placed at the end of the file

2022-06-09 12:18 UTC, ilalande submitted a review, later dismissed

2022-06-10 11:38 UTC, LuigiMenez approved these changes
Ok for me.

2022-06-10 11:43 UTC, Dash293 approved these changes

2022-06-10 11:47 UTC, LuigiMenez approved these changes
Ok for me.

2022-06-10 13:14 UTC, LoicBrassart approved these changes
SnE

2022-06-10 14:41 UTC, merged