creation pages home and caroussel
WildCodeSchool/2022-03-JS-Lille-project-3-g2-wim pull request #27
Opened 2022-06-13 08:29 UTC by n-faycel

2022-06-13 08:39 UTC, ThomasDCW submitted a review, later dismissed
ok

2022-06-13 13:43 UTC, LuigiMenez approved these changes
Sorry I didn't see the conflicts

2022-06-13 13:43 UTC, LuigiMenez requested changes
Fix conflict.

2022-06-13 14:04 UTC, ThomasDCW approved these changes

2022-06-14 10:38 UTC, LuigiMenez approved these changes
Ok for me.

2022-06-15 08:53 UTC, LoicBrassart requested changes
One fix and it's my "fault", sorry for that

2022-06-15 08:53 UTC, LoicBrassart commented on frontend/src/pages/Home/index.jsx
> +import "swiper/css/pagination";
Sorry, I should have been more explicit for this one :pray: 
```
// eslint-disable import/no-unresolved
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import { Navigation, Pagination, Mousewheel, Keyboard } from "swiper";
// eslint-enable import/no-unresolved
```

2022-06-16 07:26 UTC, closed without merging