roads to back almost finished
WildCodeSchool/2022-03-JS-Lille-project-3-g2-wim pull request #44
Opened 2022-06-16 09:48 UTC by remi59800

2022-06-16 18:02 UTC, ThomasDCW submitted a review, later dismissed

2022-06-17 09:44 UTC, LuigiMenez requested changes
No dead code

2022-06-17 11:43 UTC, Dash293 submitted a review, later dismissed

2022-06-17 11:44 UTC, ThomasDCW submitted a review, later dismissed

2022-06-17 15:23 UTC, LuigiMenez approved these changes
Ok for me

2022-06-20 08:51 UTC, LoicBrassart approved these changes
SnE, good job! ;-)

2022-06-20 14:04 UTC, ThomasDCW approved these changes
Resolve conflicts ... so here we are again

2022-06-21 10:12 UTC, LuigiMenez requested changes
Minor fix

2022-06-21 10:12 UTC, LuigiMenez commented on backend/src/router.js
> +
useless space

2022-06-21 10:12 UTC, LuigiMenez commented on backend/src/router.js
> +
Same

2022-06-21 11:35 UTC, Dash293 approved these changes

2022-06-22 09:54 UTC, LoicBrassart approved these changes
SnE

2022-06-22 10:01 UTC, LuigiMenez approved these changes
ok for me

2022-06-22 10:13 UTC, merged