LessonCard-LessonsPage-TopicPages-API-call-and-CSS-fix
WildCodeSchool/2022-03-JS-Lille-project-3-g2-wim pull request #46
Opened 2022-06-17 00:02 UTC by Dash293

2022-06-17 09:59 UTC, ThomasDCW approved these changes

2022-06-17 10:29 UTC, LuigiMenez requested changes
No review SM

2022-06-17 11:35 UTC, ThomasDCW approved these changes

2022-06-17 14:08 UTC, LuigiMenez requested changes
Attention to proofreading

2022-06-17 14:08 UTC, LuigiMenez commented on frontend/src/components/AudioPlayerLoading/index.jsx
> +    axios.get("http://localhost:5000/lessons/").then(({ data }) => {
Use .env variable

2022-06-17 14:08 UTC, LuigiMenez commented on frontend/src/components/LessonCard/index.jsx
> +    axios.get("http://localhost:5000/lessons").then(({ data }) => {
same

2022-06-17 14:08 UTC, LuigiMenez commented on frontend/src/components/LessonCard/index.jsx
> +            <img className="heart" src={EmptyHeart} alt="" />
alt for accessibility

2022-06-17 14:08 UTC, LuigiMenez commented on frontend/src/components/LessonCard/style.jsx
> +    /* border: solid 1px red; */
no dead code

2022-06-17 14:08 UTC, LuigiMenez commented on frontend/src/components/LessonCard/style.jsx
> +    /* border: solid 1px red; */
same

2022-06-17 14:08 UTC, LuigiMenez commented on frontend/src/pages/Home/index.jsx
>  }
The components is not export??

2022-06-17 14:29 UTC, ThomasDCW approved these changes

2022-06-21 12:06 UTC, ThomasDCW approved these changes

2022-06-21 13:12 UTC, closed without merging