Cretion road stream front
WildCodeSchool/2022-03-JS-Lille-project-3-g2-wim pull request #48
Opened 2022-06-17 14:58 UTC by jeremyjorand

2022-06-17 15:01 UTC, ThomasDCW submitted a review, later dismissed
ok

2022-06-17 15:40 UTC, LuigiMenez approved these changes
Ok for me.

2022-06-20 08:55 UTC, LoicBrassart requested changes
Please fix, nothing too heavy

2022-06-20 08:55 UTC, LoicBrassart commented on frontend/src/components/AudioPlayer/index.jsx
> +    axios.get(`http://localhost:5000/lessons/${id}`).then(({ data }) => {
Use a dotenv variable instead of localhost

2022-06-20 08:55 UTC, LoicBrassart commented on frontend/src/components/AudioPlayer/index.jsx
> +        <p className="topic">Mathématique</p>
Almost sure this word always ends with an "s"

2022-06-20 08:55 UTC, LoicBrassart commented on frontend/src/pages/Stream/index.jsx
> +// import img from "@assets/imgAudio.png";
Dead code!

2022-06-20 14:59 UTC, ThomasDCW approved these changes

2022-06-21 10:02 UTC, LuigiMenez commented on frontend/src/pages/Stream/index.jsx
> +// import img from "@assets/imgAudio.png";
Why is it still there?

2022-06-22 07:49 UTC, ThomasDCW approved these changes
ok

2022-06-22 08:33 UTC, LuigiMenez approved these changes
Ok, but beware of the unnecessary blank line.

2022-06-22 10:05 UTC, LoicBrassart approved these changes
SnE

2022-06-22 10:14 UTC, merged