002 navigation routes
WildCodeSchool/2022-03-JS-Lille-project-3-g2-wim pull request #5
Opened 2022-06-01 13:34 UTC by remi59800

2022-06-01 13:50 UTC, ThomasDCW approved these changes

2022-06-02 07:54 UTC, LuigiMenez requested changes
Use absolute please imports, and avoid using <Style> as a tag in your components, customise them.

2022-06-02 07:54 UTC, LuigiMenez commented on frontend/src/App.jsx
> +import Header from "./components/Header";
Use absolute please imports

2022-06-02 07:54 UTC, LuigiMenez commented on frontend/src/pages/Home/index.jsx
> +    <Style>
Avoid using <Style> as a tag in your components, customise them.

2022-06-02 09:44 UTC, remi59800 reviewed
fix absolut import and name balise Style

2022-06-02 09:57 UTC, closed without merging