005 inscription enregistrement
WildCodeSchool/2022-03-JS-Lille-project-3-g2-wim pull request #55
Opened 2022-06-22 13:49 UTC by ilalande

Part 2 of login and checking : finishing connect and fixing bugs

2022-06-23 07:24 UTC, ThomasDCW submitted a review, later dismissed
ok for me

2022-06-23 14:13 UTC, LoicBrassart requested changes
Stop `git add .` :tired_face:

2022-06-23 14:18 UTC, ThomasDCW commented on dd
> +  axios[m
dunno ...

2022-06-23 14:46 UTC, ThomasDCW approved these changes

2022-06-24 13:36 UTC, LoicBrassart approved these changes
SnE

2022-06-24 13:36 UTC, merged