create header
WildCodeSchool/2022-03-JS-Lille-project-3-g2-wim pull request #6
Opened 2022-06-01 14:04 UTC by jeremyjorand

2022-06-01 20:04 UTC, ThomasDCW approved these changes

2022-06-02 07:56 UTC, LuigiMenez approved these changes
Used styled-components instead of app.css

2022-06-02 07:56 UTC, LuigiMenez commented on frontend/src/App.jsx
>        <p>coucou</p>
Don't forget to remove the "Coucou"

2022-06-02 08:01 UTC, LoicBrassart requested changes
No vanilla css file !

2022-06-02 08:01 UTC, LoicBrassart commented on frontend/src/App.css
> +@import url("https://fonts.googleapis.com/css2?family=Poppins&display=swap");
No CSS file, plz use styled-components

2022-06-07 07:40 UTC, ThomasDCW approved these changes
looks ok

2022-06-07 07:59 UTC, LuigiMenez approved these changes
Ok for me.

2022-06-07 08:00 UTC, LuigiMenez requested changes
Fix conflict

2022-06-07 08:14 UTC, ThomasDCW approved these changes
i fixed conflicts

2022-06-07 13:54 UTC, LoicBrassart approved these changes
SnE

2022-06-07 14:18 UTC, merged