Administrationhome
WildCodeSchool/2022-03-JS-Lille-project-3-g2-wim pull request #63
Opened 2022-06-27 09:02 UTC by ThomasDCW

On product backlog branch 021-administration-home

Install React admin, for now there is a page where we get list for users, topics, lessons

NEXT step auth in react admin 
cf Backlog -> 022-administration-authentification
I guess we need a user who get the right in db or somewhere...

I had an error in console when i use import "@servicec/api" so i was obliged to use "../services/api"

2022-06-27 09:42 UTC, jeremyjorand approved these changes
ok for me

2022-06-28 08:23 UTC, LuigiMenez requested changes
Use import absolute

2022-06-28 08:23 UTC, LuigiMenez commented on admin/src/dataProvider.js
> +import api from "../services/api";
Use import absolute

2022-06-28 08:23 UTC, LuigiMenez commented on admin/vite.config.js
> +const path = require('path');
You can't use the imports instead of the require?

2022-06-28 10:22 UTC, jeremyjorand approved these changes
ok for me

2022-06-28 15:26 UTC, LuigiMenez approved these changes
Ok for me

2022-07-04 07:53 UTC, Dash293 approved these changes

2022-07-05 07:28 UTC, LoicBrassart approved these changes
SnE

2022-07-05 07:28 UTC, LoicBrassart commented on admin/src/App.jsx
> +        <Resource name="topics" list={ListGuesser} />
You'll have to rewrite these *Guessers later

2022-07-05 07:28 UTC, LoicBrassart commented on admin/src/authProvider.js
> +      localStorage.setItem("token", data.token);
NB: You know how to register a token in a LocalStorage (as an answer to this morning's stand-up)

2022-07-05 07:29 UTC, merged