Subjects links and lessons filtering
WildCodeSchool/2022-03-JS-Lille-project-3-g2-wim pull request #65
Opened 2022-06-28 10:19 UTC by Dash293

2022-06-28 12:11 UTC, ThomasDCW approved these changes
SnE

2022-06-28 15:40 UTC, LuigiMenez requested changes
Fix conflict

2022-07-04 08:53 UTC, LuigiMenez approved these changes
Ok for me.

2022-07-05 07:31 UTC, LoicBrassart approved these changes
SnE

2022-07-05 07:32 UTC, merged