Authentificationsecurise
WildCodeSchool/2022-03-JS-Lille-project-3-g2-wim pull request #66
Opened 2022-07-04 07:40 UTC by ThomasDCW

2022-07-04 07:57 UTC, Dash293 approved these changes

2022-07-04 09:02 UTC, LuigiMenez approved these changes
Ok for me.

2022-07-05 07:35 UTC, LoicBrassart requested changes
ALAAAAAAAAAAAAAARRRRRMMMMMMMMMM !!!!!!!!!!

2022-07-05 07:35 UTC, LoicBrassart commented on admin/.env
> +/admin
:scream: 
WHY IS THERE A .ENV FILE HERE ?!
@LuigiMenez ! SOMEONE!!! ALAAAAARM !!!!!!! :skull: :warning:

2022-07-05 07:35 UTC, LoicBrassart commented on frontend/src/components/SignIn/index.jsx
> +      .post("http://localhost:5000/auth/login", formData)
Don't use "http://localhost:5000" anymoe, use env variables

2022-07-05 09:31 UTC, Dash293 approved these changes

2022-07-05 13:13 UTC, LuigiMenez submitted a review, later dismissed
Okk for me.

2022-07-06 06:56 UTC, LoicBrassart requested changes
When asked to improve a bit of code, you should not implement *new features*: if you miss something, the whole PR is held back

2022-07-06 06:56 UTC, LoicBrassart commented on frontend/src/components/SignIn/index.jsx
> +        toast("Wow so easy!");
Customize this message

2022-07-06 06:56 UTC, LoicBrassart commented on frontend/src/components/SignIn/index.jsx
> +        toast.error("Aww, it broke!");
Same

2022-07-06 09:05 UTC, ilalande submitted a review, later dismissed

2022-07-06 14:04 UTC, LuigiMenez submitted a review, later dismissed
Ok for me.

2022-07-06 14:06 UTC, LoicBrassart approved these changes
SnE

2022-07-07 09:06 UTC, LuigiMenez requested changes
Two toastContainer?

2022-07-07 09:06 UTC, LuigiMenez commented on frontend/src/main.jsx
> +      <ToastContainer />
Why 2 toastContainer?

2022-07-07 13:30 UTC, LuigiMenez approved these changes
Ok for me.

2022-07-11 08:01 UTC, LoicBrassart approved these changes
SnE

2022-07-11 08:06 UTC, merged