feature done
WildCodeSchool/2022-03-JS-Lille-project-3-g2-wim pull request #72
Opened 2022-07-06 10:32 UTC by Dash293

2022-07-07 07:49 UTC, ThomasDCW approved these changes
ok

2022-07-07 07:57 UTC, ThomasDCW submitted a review, later dismissed
okokok

2022-07-07 09:34 UTC, LuigiMenez requested changes
Not " ! " in the route

2022-07-07 09:34 UTC, LuigiMenez commented on backend/src/router.js
> +router.get("/!empty-topics", TopicHaveLessonController.browse);
Not " ! " in the route

2022-07-11 08:02 UTC, LoicBrassart approved these changes
SnE

2022-07-11 08:07 UTC, merged