Fix backend
WildCodeSchool/2022-03-JS-Lille-project-3-g2-wim pull request #75
Opened 2022-07-07 07:44 UTC by Dash293

2022-07-07 07:45 UTC, ThomasDCW submitted a review, later dismissed
ok

2022-07-07 09:12 UTC, LuigiMenez requested changes
Fix minor

2022-07-07 09:12 UTC, LuigiMenez commented on backend/src/models/FavoriteManager.js
> +      `select lesson.id, lesson.fileName, lesson.schoolTopic_id, lesson.title, lesson.subTitle, lesson.musicStyle, lesson.fileLocation, lesson.lyrics, lesson.img, lesson.duration, lesson.schoolClass_
Are you still looking for the data of user id 1?

2022-07-07 09:43 UTC, ThomasDCW approved these changes
ok for me

2022-07-07 09:46 UTC, LuigiMenez approved these changes
Ok for me.

2022-07-11 08:07 UTC, LoicBrassart approved these changes
SnE

2022-07-11 08:43 UTC, merged