fix Css Subject
WildCodeSchool/2022-03-JS-Lille-project-3-g2-wim pull request #78
Opened 2022-07-08 12:56 UTC by jeremyjorand

2022-07-08 12:59 UTC, ThomasDCW approved these changes
Ok

2022-07-11 08:10 UTC, LuigiMenez requested changes
Fix conflict

2022-07-11 10:12 UTC, ThomasDCW approved these changes
ok

2022-07-11 14:11 UTC, LoicBrassart approved these changes
SnE

2022-07-11 14:17 UTC, merged