Add delete favoris end
WildCodeSchool/2022-03-JS-Lille-project-3-g2-wim pull request #90
Opened 2022-07-12 14:47 UTC by ilalande

2022-07-12 15:04 UTC, ThomasDCW submitted a review, later dismissed
ok

2022-07-13 07:53 UTC, LuigiMenez requested changes
Fix conflict

2022-07-13 09:18 UTC, ThomasDCW approved these changes
ok

2022-07-13 10:37 UTC, LuigiMenez requested changes
Fix minor

2022-07-13 10:37 UTC, LuigiMenez commented on backend/src/models/FavoriteManager.js
> +      `DELETE FROM userFavLesson $ WHERE lesson_id = ? AND user_id = ?`,
Nop $

2022-07-13 13:40 UTC, ThomasDCW approved these changes
ok

2022-07-13 13:48 UTC, LuigiMenez approved these changes
Ok for me.

2022-07-18 08:50 UTC, LoicBrassart approved these changes
SnE

2022-07-18 08:52 UTC, merged

2022-07-18 09:19 UTC, LoicBrassart reviewed
SnE